apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bus2
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: bus2
    app.kubernetes.io/part-of: app-taxi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bus2
      app.kubernetes.io/part-of: app-taxi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: bus2
        app.kubernetes.io/part-of: app-taxi
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/div/nationalparks-py:latest
        imagePullPolicy: Always
        name: bus
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
