apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-demo-dev-bus
  namespace: demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgA78LW0VA4Mh4NFPkZjGna9wkltnSM1JT4RAYLyKBCkAyMm06gyjMONwKfsKeFmn5ahTu+v3CH1bJSOS/2CFlFrvVCu/HLAYkePWeAGl1r0H9CV+vjkI07H0D9PieMNX7Cu1rQbkwvlKw7+rHntzIv/nFfechrMGWz/3jZJcZ115b2oEml4D65s7o/opcvERYOrekPg5l9VpPBwrr3K+gtAQSfu3pJ9srmgh1NPstfm+oFdxiBCA6+KvZSM7D0x4qWwGa6i2SLwHS1B8frY1JFPzd9sjCc1LhRp0lcER6MEl+ZnWLh574pinjqU51HczhTUIcGoiP1kP/+te8eAWr7cHYRBVkT5esrHvePnC0bvlabX8wE2LM3z8jNQuL65tJnU8r2n3Tcdnvqgp8t2uoSCmpkmX3Xb87aWJYMnKYPCTibCTRkbcCsSH5s9pWh5N3k+RlCZjzrQJ0rFgrnMI17OBf2ATVsLzBt65LzRZQBdHjbYcMjCLIIXq6IPME3U66d8zUUX1Cz0nh6ENcDZJnI6kBoo/Pfuk10f3WlkQ4Ob/pXhFsiukLT0LZU1+LU+de6GpFOheo7qgT8QC9qchTNwYt34jKh2G7IXxjORqBN0b2xbLLp55rDj9/MoHwF1uQ4XU/2V8aKa/tYcZlMTJ+x9oHvGPaZIwzC44R3fqHGNKezGIxou/PkigqDcyFjulm7wmcevPW2raKRFmTxTZ/cvkuJB1g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-demo-dev-bus
      namespace: demo-cicd
    type: Opaque
status: {}
