apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-demo-stage-taxi
  namespace: demo-cicd
spec:
  encryptedData:
    webhook-secret-key: AgAu94O7yC+LqjdjGnhe/f9wbxmj9LlB0CXqwdSzsIvnfMpqtnqrYYs3/rRB3SJO0vUpHVYAPwaEZJWVM4/BXPcc12s5fPbRNAPye8n4r0/+zx7LCUXbAaxgA8a/QzRtOSmY3BdNehhFO2orUV0sdtmRdy3jUDVLxOkubsb5eDLTobfnRW1BgGy+wKXg+ZgSpAfOtga56/rCCmZttbxcaZz3FYCOVOpiqxzb8wZUz3ir4284QBxaYGexmfV9mbgxpWQzU26Ctq1lpfbsGU34OYz2tWW0CFwipzSt47zqNyapDjyqaM0QLE0S1AcYMhs0NNcKCKzqgnDlpvj1TNA9rGi890QDNk43pBcFYGpLcFQsWhDGcYB/8tMAftSGSuT4P4eOHKHnOriWac72JobrJW05y03DlJTYAQ0Dz8QZFfEXjnesDyU/O0zer4AkKZyyAaVL+FJzw6UR6cso1zaRz2GEFgj4FMFMU3y+JZlfH2QAKFMJZBrjKlm/dCfSa/GI7wGZSpiiz/Pt4ELkR3WaeR2fwtUK+/Sxmi36GZEzu7H7PnXQA44yXdXMbHu8EpqsEMHEfGeqY8QeKgY7N+3mdQPo9uE8WoLbHBcyb/hp8xPLd9x2v+PkDT9M76A58sp4AlFiNFq+rkMXkWFGCQt1wEIugwXN+WONpC5O43v1vBnp5MejnPamzdB2KI+ncVg5dTY=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-demo-stage-taxi
      namespace: demo-cicd
    type: Opaque
status: {}
