apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-new-env-bus
  namespace: tst-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBNcK2sug16JIsI8rPOuVc7SR1lwSEDprrVVSMJoz0Db/AWEoGtcHIE2CeyqA9jLzIvICej+1o76Flfh2Nm0Guy6opLdg//0sPGkbi5wU5bbfAMxudj885y1OeFUdKijZjQHx5TmTra4IqdiMI423y1at7wgWPQCYPXRpF80z1sgpc1PrlhsYDidNtEMDaGmpWtGklQBDE4z70ykg3FmxP1g0kBI+fYTxwIqSKUFYhWJ5dbKWopvYeIyv9zbXySdc69DOMOH33Wvu1iUBUSwFQbQpwUMeubbCgubYeIvJpheVxxh9ce5qOL2Jj8zNAWYFoH/AXLCf0qsmK9NEQgMvit9rIKO6XkT5BDnzO7W8hJ5c2dAXZs94jG3jmxZv1Ci7PcKJpP0hIwSQiTRQJm25v0tyxq66MsammQWILTMHnI1OA77NX3tcfSmGUpzU+I/301JXFzUTv+ln3OtJY2LplnZ//vXClCkEbLA/5R6BrO26Vlz8Dv+FbgNnwySma6Pqyc//RgaCBK4yqRhNGSSiTW8b5u9YHiLaIH+AaAHKYQTSPfTiKh6MH0URiW4oL3PzrAabjxcF5fQtwemdmyEOoMdCVTWuBZ2sONdMWvQqFMgu3+ZZRSqxdk4vZGleYsBl5eYHt9lYpi6Z38agBO3TCRJw9J/e3BTLILYy7GAMP/I7fPi9Fmc792ZJkUrJ2lTt+GXdHJ1gTkmE9x+M8mCIV1Up90Ug==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-new-env-bus
      namespace: tst-cicd
    type: Opaque
status: {}
