apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-tst-dev-taxi
  namespace: tst-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCl+FRIyKq6pwt5GMJeB0rCQYNs6pqGuAmH/yps+n7hFQOJnFPL/vWyjtkwXnJW/rFCcewJgLxs7b7DR5bKAHbWkZS5cqDMYyhtiSGs7o+kzyFFMsfdnX9NRRFwybt2YmrVtvF8tY8asd34kLxK1CEfiyGIYVcz2GcDOyl7Id5jvIY1g60j03SfZPKopEA3fb1zp1BEeLuuW+qdSynU4/0bHQk1jLxmMPC9zLODsnt4m+ny/FvHdaf0gjiARErnNwdiMYQhw4HU0oWX98yLQomVgQrNtsPMZVu7vpBHo4E6PD5KA8XueQRsCgCkeiY1jkxq1Kqx0vYMAjnKd5uVwZ2mrnyMQ1epQfYwYUpPycTkMib0g80L/dFViUBkZJIkzp7Ewq02cSLO12gjyb5s9XsfSthwqMTA6fZBs3QZ8xjeSVLytxN2HflP8cCAfgg+fUkvLZseBAXnDCHhYZwEq8DC2ub4SI0d0t1PRyr9Eo2FT6CgZNRehdBPNqrKPDpv12HZRqN3Yz2pzW/G3KiIEBXhKcmlGOBZ21iRgNpd2qzka6xZYd36uuEo1EeW3kJDWuR8L/Ml6PiSbXkgOWI6dkrTaLd0Bm8rh2Li8+D/ppFhjfovoKAeliVRjr3Y0LaZAir63j0ic+9K6FceO8SxEL++X2GghOO+UJv5l1ozMc3xO0J+nJnFbTsUOh/sNEHHJ51moJYAuZSky+lvBWLwHuvp6lLr6g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-tst-dev-taxi
      namespace: tst-cicd
    type: Opaque
status: {}
